#cloud-config

hostname: hypervisor
fqdn: hypervisor.local
manage_etc_hosts: true

# timezone: set the timezone for this instance
timezone: UTC

# recreate server ssh keys
ssh_deletekeys: 1

users:
  - name: centos
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVmP5DHNIq466ZTeR04JC8gVCZxtgnHOLw3903HXDvi8dFTggfNKGYew3CBaZqfvkGeAkOihbabK1eXEbwL2J7SuHdp90ug3ocDSfanFyvDz4WdAIC3VOinX1GvYTKL0w6ljSQQWpGuzCFDb+guaOWJCkkForac29xxgQUbDhuUUaBF+ET3J9F9u79dwBgxlV0MXsW8I3m0XiSdUupQNFXdlCzOMHc8wOdqV0pOnrW3PHt391f0FearKqY2ktyD7gbAhf5m98OvDpYl2d5DOiIfs+uCWeC3qAYf0wv87pV1dhWy+F0KMcevj05vetuEtScf9L2DCRvuPFVlEY/5nxqjv2VSwHnJyB3umHxKVNX6Xg9BC6M50jjAdW1Mx6JP1zp/k7g9AUZSeTNGWbzZEDJ7sDcJdmLpUg7tqMFB0Xp9ifmVCBhgzcG69RedNLIO6uH11Ewx3BO62PSB8GyB3FnaUoOwTZGWzxJPFPdos+KxFsbsX57RICxKqCdWyqF+YK+jb9j4xTxf2Vu8aFlc8EOXnMv4as8U9+r05usyWVSwVdYosK9fchJzgPhoXzkgRbN3XA0nA5GGhtr2arb9qnSzKcyH0d0r8J0LfN9Ifh+5dZD5SkRUmonlvcdXccdC1FpA95MALofVlvVeYperYLeG1Zg1yRADoBDalVswtdW9Q== vagrant
packages:
  - docker
  - git
runcmd:
  - chkconfig docker on
